"""refactor resume design

Revision ID: bbfb9c74ca19
Revises: 337eaade2697
Create Date: 2024-09-19 00:08:05.910313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbfb9c74ca19'
down_revision: Union[str, None] = '337eaade2697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leads', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'resumes', ['resume_id'], ['id'])
    op.drop_column('leads', 'resume_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('resume_location', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'resume_id')
    op.drop_table('resumes')
    # ### end Alembic commands ###
