version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alma
      MYSQL_USER: alma
      MYSQL_PASSWORD: alma
    ports:
      - "3306:3306"